export const ALL_BATCH_REQUEST = "ALL_BATCH_REQUEST";
export const ALL_BATCH_SUCCESS = "ALL_BATCH_SUCCESS";
export const ALL_BATCH_FAIL = "ALL_BATCH_FAIL";

export const REGISTER_BATCH_REQUEST = 'REGISTER_BATCH_REQUEST';
export const REGISTER_BATCH_SUCCESS = 'REGISTER_BATCH_SUCCESS';
export const REGISTER_BATCH_FAIL = 'REGISTER_BATCH_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";