export const ALL_STUDENTS_REQUEST = "ALL_STUDENT_REQUEST";
export const ALL_STUDENTS_SUCCESS = "ALL_STUDENT_SUCCESS";
export const ALL_STUDENTS_FAIL = "ALL_STUDENT_FAIL";

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const DELETE_STUDENT_REQUEST = 'DELETE-STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE-STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE-STUDENT_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";