export const ALL_STUDENTS_REQUEST = "ALL_STUDENT_REQUEST";
export const ALL_STUDENTS_SUCCESS = "ALL_STUDENT_SUCCESS";
export const ALL_STUDENTS_FAIL = "ALL_STUDENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";