export const ALL_VIDEO_REQUEST = 'ALL_VIDEO_REQUEST';
export const ALL_VIDEO_SUCCESS = 'ALL_VIDEO_SUCCESS';
export const ALL_VIDEO_FAIL = 'ALL_VIDEO_FAIL';

export const REGISTER_VIDEO_REQUEST = 'REGISTER_VIDEO_REQUEST';
export const REGISTER_VIDEO_SUCCESS = 'REGISTER_VIDEO_SUCCESS';
export const REGISTER_VIDEO_FAIL = 'REGISTER_VIDEO_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";
